name: Generate Snake Animation

on:
  schedule:  # Execute every 12 hours
    - cron: "* */12 * * *"  # Cron expression for every 12 hours
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  generate:
    permissions:
      contents: write  # Allow writing to the repository contents
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Timeout for the job after 5 minutes

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3  # Action to generate the snake animation as SVG
        with:
          github_user_name: ${{ github.repository_owner }}  # Get the repository owner's username
          outputs: dist/snake.svg?palette=github-dark  # Output location and palette for the snake

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0  # GitHub Pages action to deploy to the `output` branch
        with:
          target_branch: output  # Target branch for GitHub Pages
          build_dir: dist  # Directory to push the generated SVG from
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication

